#!/bin/bash
FILES=files
TMP=/tmp
STORE=$TMP/compare.store
TIME=/usr/bin/time

SUITE=$1

# Check input
if [ -z "$SUITE" ]; then
    echo "Usage: compare <suite-file>"
    exit 1
fi

if [ ! -f $SUITE ]; then
    echo "Suite file not found: $1"
    exit 1
fi

# Execute command suite
FILENAMES=`ls $FILES`
for F in $FILENAMES; do

IN=files/$F
INSZ=`du -b $IN | cut -f 1`

echo
echo "$IN ($INSZ bytes) ..."
echo
printf "%16s | %10s | %10s | %9s | %10s | %10s\n" "" "C Time" "C Memory" "C Rate" "D Time" "D Memory"
printf "=%.0s" {1..80}
echo

while read LINE; do
    # parse compressor info
    IFS=";" read -r NAME MODE EXT CCMD DCMD <<< "$LINE"

    if [ -z "$NAME" -o -z "$EXT" -o -z "$CCMD" -o -z "$DCMD" ]; then
        printf "%80s\n" "(incomplete command info in suite)"
        continue
    fi

    # determine output file and delete it if it still exists
    OUT=$TMP/$F$EXT
    rm -f $OUT

    # specify command
    CCMD=${CCMD/@IN/$IN}
    CCMD=${CCMD/@OUT/$OUT}
    DCMD=${DCMD/@IN/$OUT}

    # print name
    printf "%16s" $NAME

    # compress
    if [ "$MODE" == "stdout" ]; then
        $TIME -f "%U;%M" -o $STORE $CCMD >$OUT 2>/dev/null
        OK=$?
    else
        $TIME -f "%U;%M" -o $STORE $CCMD >/dev/null 2>&1
        OK=$?
    fi

    if [ $OK -ne 0 ]; then
        printf " |%62s\n" "(compress error)"
        continue
    fi

    IFS=";" read -r TM MEM < $STORE

    # print runtime and memory usage
    printf " | %#8.2f s | %8d K" $TM $MEM

    if [ ! -f $OUT ]; then
        printf " |%36s\n" "($OUT not found)"
        continue
    fi

    # calculate compression rate
    OUTSZ=`du -b $OUT  | cut -f 1`
    RATE=`echo 100*$OUTSZ/$INSZ | bc -l`

    # print name and compression rate
    printf " | %8.4f%%" $RATE

    # decompress
    $TIME -f "%U;%M" -o $STORE $DCMD >/dev/null 2>&1
    OK=$?

    if [ $OK -ne 0 ]; then
        printf " |%24s\n" "(decompress error)"
        continue
    fi

    IFS=";" read -r TM MEM < $STORE

    # print runtime and memory usage
    printf " | %#8.2f s | %8d K\n" $TM $MEM

done < $1 # suite
done # files
